# Generated by Django 5.0.3 on 2024-08-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_mychats_chats_mychats_created_at_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mychats',
            name='created_at',
        ),
        migrations.AddField(
            model_name='mychats',
            name='chats',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
