# Generated by Django 4.2.4 on 2024-12-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_group_groupmember_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
