# Generated by Django 4.2.4 on 2024-12-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_message_is_archived_message_is_starred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='edit-profile/'),
        ),
    ]
